/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MotorInsuranceRouteImport } from './routes/motor-insurance'
import { Route as LifeInsuranceRouteImport } from './routes/life-insurance'
import { Route as InsuranceDashboardRouteImport } from './routes/insurance-dashboard'
import { Route as HealthInsuranceRouteImport } from './routes/health-insurance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorInsuranceRoute = MotorInsuranceRouteImport.update({
  id: '/motor-insurance',
  path: '/motor-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeInsuranceRoute = LifeInsuranceRouteImport.update({
  id: '/life-insurance',
  path: '/life-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceDashboardRoute = InsuranceDashboardRouteImport.update({
  id: '/insurance-dashboard',
  path: '/insurance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInsuranceRoute = HealthInsuranceRouteImport.update({
  id: '/health-insurance',
  path: '/health-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/motor-insurance': typeof MotorInsuranceRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/motor-insurance': typeof MotorInsuranceRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/motor-insurance': typeof MotorInsuranceRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claims'
    | '/contact'
    | '/health-insurance'
    | '/insurance-dashboard'
    | '/life-insurance'
    | '/motor-insurance'
    | '/services'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claims'
    | '/contact'
    | '/health-insurance'
    | '/insurance-dashboard'
    | '/life-insurance'
    | '/motor-insurance'
    | '/services'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/claims'
    | '/contact'
    | '/health-insurance'
    | '/insurance-dashboard'
    | '/life-insurance'
    | '/motor-insurance'
    | '/services'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClaimsRoute: typeof ClaimsRoute
  ContactRoute: typeof ContactRoute
  HealthInsuranceRoute: typeof HealthInsuranceRoute
  InsuranceDashboardRoute: typeof InsuranceDashboardRoute
  LifeInsuranceRoute: typeof LifeInsuranceRoute
  MotorInsuranceRoute: typeof MotorInsuranceRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motor-insurance': {
      id: '/motor-insurance'
      path: '/motor-insurance'
      fullPath: '/motor-insurance'
      preLoaderRoute: typeof MotorInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-insurance': {
      id: '/life-insurance'
      path: '/life-insurance'
      fullPath: '/life-insurance'
      preLoaderRoute: typeof LifeInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-dashboard': {
      id: '/insurance-dashboard'
      path: '/insurance-dashboard'
      fullPath: '/insurance-dashboard'
      preLoaderRoute: typeof InsuranceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-insurance': {
      id: '/health-insurance'
      path: '/health-insurance'
      fullPath: '/health-insurance'
      preLoaderRoute: typeof HealthInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClaimsRoute: ClaimsRoute,
  ContactRoute: ContactRoute,
  HealthInsuranceRoute: HealthInsuranceRoute,
  InsuranceDashboardRoute: InsuranceDashboardRoute,
  LifeInsuranceRoute: LifeInsuranceRoute,
  MotorInsuranceRoute: MotorInsuranceRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
